name: Publish Documentation

on:
  push:
    branches: [ main ]
  paths:
      - Docs/**

  workflow_dispatch:

jobs:
  deploy_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material==7.3.4
      - run: pip install pymdown-extensions==6.0
      - run: mkdocs gh-deploy --force -m "[ci skip]"
        working-directory: Docs
